# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-01 04:33
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DebaterPreference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('debater_preference', models.CharField(max_length=255, unique=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Judge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SignUpPreference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('debater_preference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.DebaterPreference')),
                ('member_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='api.Member')),
                ('partner_preference', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='api.Member')),
            ],
        ),
        migrations.CreateModel(
            name='SkillLevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_level', models.CharField(max_length=255, unique=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SortedRoom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('debater_one_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='debater_one', to='api.Member')),
                ('debater_two_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='debater_two', to='api.Member')),
                ('skill_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.SkillLevel')),
            ],
        ),
        migrations.CreateModel(
            name='VPIPreference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judgeless_rooms', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('room_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.SkillLevel')),
            ],
        ),
        migrations.AddField(
            model_name='sortedroom',
            name='cg_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='CG', to='api.Team'),
        ),
        migrations.AddField(
            model_name='sortedroom',
            name='co_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='CO', to='api.Team'),
        ),
        migrations.AddField(
            model_name='sortedroom',
            name='og_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='OG', to='api.Team'),
        ),
        migrations.AddField(
            model_name='sortedroom',
            name='oo_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='OO', to='api.Team'),
        ),
        migrations.AddField(
            model_name='sortedroom',
            name='room_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Room'),
        ),
        migrations.AddField(
            model_name='sortedroom',
            name='skill_level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.SkillLevel'),
        ),
        migrations.AddField(
            model_name='member',
            name='skill_level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.SkillLevel'),
        ),
        migrations.AddField(
            model_name='member',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='judge',
            name='member_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Member'),
        ),
        migrations.AddField(
            model_name='judge',
            name='sorted_room_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.SortedRoom'),
        ),
    ]
